### ISSUE TITLE
perfplot

### ISSUE THREAD

**Issue by nschloe** [MSeifert04/simple_benchmark#3]
Not sure if you knew, but I guess a small heads-up for perfplot https://github.com/nschloe/perfplot. Seems to do about the same thing as simple_benchmark.

**Comment by MSeifert04** [comment]
Hi @nschloe, nice to here from you.

Yep, `simple_benchmark` does the same as `perfplot` in a slightly different way (at least with a slightly different API). I only learned about your library after I've created my own, otherwise I probably wouldn't have written my own lib.

But thanks for bringing this to my attention again - I've meant to cross-link your library in the docs (or readme) and always forgot. I'll do so shortly.

**Comment by MSeifert04** [comment]
Again I forgot about it. But now I finally managed to put a reference to perfplot in the ReadMe.
